add some new
Andrii-Mudrak/my_project pull request #2
Opened 2020-10-23 20:37 UTC by Andrii-Mudrak

Add some changes.
please check setting.py
for continuation must change databases connection.

2020-10-24 12:45 UTC, TihonV requested changes

2020-10-24 12:45 UTC, TihonV commented on mainapp/migrations/0002_auto_20201023_1819.py
> +# Generated by Django 3.1.2 on 2020-10-23 18:19
Варто поєднати міграції за допомогою `squashmigrations`.

2020-10-24 12:45 UTC, TihonV commented on mainapp/migrations/0002_auto_20201023_1819.py
> +            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 18, 19, 39, 381122)),
Бачу помилку в моделях. Напевно відбувається наступне:
```python3
created_at = models.DateTimeField(default=datetime.now())  
# вираховується лише при першому імпорті модулю
```

Замість 
```python3
created_at = models.DateTimeField(default=datetime.now)  # вираховується кожен раз
```

2020-10-24 12:45 UTC, TihonV commented on mainapp/models.py
>  class User(models.Model):
Використовуй відповідні назви для моделей. Це не модель користувача, а його профіль. Зміни назву щоб не плутатись із AUTH_USER_MODEL.

2020-10-24 12:45 UTC, TihonV commented on mainapp/models.py
> +    password1=models.CharField(max_length=20, help_text='Input a passaword')
first_name, last_name, email, password частина AUTH_USER_MODEL. Не бачу причин для їх дублювання.

2020-10-24 12:45 UTC, TihonV commented on mainapp/templates/mainapp/signup.html
> +    <p style="color: red">{{ error }}</p>
Зверни увагу на форматування.

2020-10-24 12:45 UTC, TihonV commented on mainapp/views.py
> +            return redirect('/')
Краще шукати параметр запиту redirect і виконувати редірект на нього.

2020-10-26 06:32 UTC, Andrii-Mudrak commented on mainapp/migrations/0002_auto_20201023_1819.py
> +            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 18, 19, 39, 381122)),
fixed

2020-10-26 06:32 UTC, Andrii-Mudrak commented on mainapp/models.py
>  class User(models.Model):
fixed

2020-10-26 06:32 UTC, Andrii-Mudrak commented on mainapp/models.py
> +    password1=models.CharField(max_length=20, help_text='Input a passaword')
fixed

2020-10-26 06:33 UTC, Andrii-Mudrak commented on mainapp/templates/mainapp/signup.html
> +    <p style="color: red">{{ error }}</p>
fixed

2020-10-26 06:33 UTC, Andrii-Mudrak commented on mainapp/views.py
> +            return redirect('/')
fixed

2020-10-26 09:33 UTC, TihonV requested changes

2020-10-26 09:33 UTC, TihonV commented on mainapp/migrations/0002_auto_20201023_1819.py
> +            field=models.DateTimeField(default=datetime.datetime(2020, 10, 23, 18, 19, 39, 381122)),
Виправ відповідно до змін міграції

2020-10-26 09:33 UTC, TihonV commented on mainapp/models.py
> +    created_at = models.DateTimeField(default=datetime.now())
Знову, та сама помилка. Має бути — `models.DateTimeField(default=datetime.utcnow)`. 
**Не викликай метод, що повертає дату.**

2020-10-26 09:33 UTC, TihonV commented on mainapp/models.py
>  class User(models.Model):
Не бачу опублікованих змін.

2020-10-26 09:33 UTC, TihonV commented on my_project/dj_database_url.py
> +# -*- coding: utf-8 -*-
Цього файла не має тут бути. В тебе — встановлюється пакет dj-database-url.

2020-10-26 09:33 UTC, TihonV commented on my_project/settings.py
> +#DATABASES = dj_database_url.config('sqlite://:db.sqlite3:',conn_max_age=0)
Не включай локальні налаштування до комміту

2021-02-20 21:00 UTC, closed without merging