Authentication
Andrii-Mudrak/my_project pull request #4
Opened 2020-10-31 21:31 UTC by Andrii-Mudrak

2020-11-05 21:01 UTC, TihonV requested changes

2020-11-05 21:01 UTC, ityshchenko commented on mainapp/models.py
> +    id = models.BigAutoField('id',primary_key=True)
missed whitespace after comma

2020-11-05 21:01 UTC, ityshchenko commented on mainapp/models.py
> +    autor_id = models.ForeignKey('User_agent', on_delete=models.SET_NULL, null=True)
All database fields are prefer lower case for column name.

2020-11-05 21:01 UTC, ityshchenko commented on mainapp/models.py
> +    autor_id = models.ForeignKey('User_agent', on_delete=models.SET_NULL, null=True)
For [Django expected](https://docs.djangoproject.com/en/3.1/ref/models/relations/) `author` instead of `author_id`.

2020-11-05 21:01 UTC, ityshchenko commented on mainapp/models.py
> +    user_id = models.ForeignKey('User_agent', on_delete=models.SET_NULL, null=True)
1. `user` instead of `user_id`
2. Use 1-to-1 field directly. See comment above.
```python3
user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
```

2020-11-05 21:01 UTC, ityshchenko commented on mainapp/templates/mainapp/basic.html
> +        {% endif%}
Missed whitespace

2020-11-05 21:01 UTC, ityshchenko commented on mainapp/templates/mainapp/basic.html
> +            <div class="d-flex d-flex justify-content-around align-items-center">
Repeats classes.

2020-11-05 21:01 UTC, ityshchenko commented on mainapp/templates/mainapp/home.html
> +{% endblock %}
No newline at end of file

2020-11-05 21:01 UTC, ityshchenko commented on mainapp/templates/registration/login.html
> +{% endblock %}
No newline at end of file

2020-11-05 21:01 UTC, ityshchenko commented on mainapp/templates/registration/login.html
> +    <a href="/
No newline in string attribute.

2020-11-05 21:01 UTC, ityshchenko commented on mainapp/templates/registration/password_reset_confirm.html
> +            {{form.as_p}}
missed whitespaces.

2020-11-05 21:01 UTC, ityshchenko commented on mainapp/templates/registration/password_reset_confirm.html
> +        <p style="color:red;">Неправильний токен</p>
Better to use bootstrap alert instead of inline styles.

2020-11-05 21:01 UTC, ityshchenko commented on mainapp/templates/registration/password_reset_email.html
> +{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
You don't need pass protocol & domain for link.

```
<a href="{{ request.scheme }}://{{ request.get_host }}{% url 'password_reset_confirm' uidb64=uid token=token %}/">Confirm account</a>
```

2020-11-05 21:01 UTC, ityshchenko commented on mainapp/views.py
Two spaces before/after `def`-block.

2020-11-05 21:01 UTC, ityshchenko commented on my_project/settings.py
> +#DATABASES['default'] = dj_database_url.config(os.getenv('DATABASE_URL', 'sqlite:///./db.sqlite3'))
Why you use default database config style instead of `DATABASE_URL`

2020-11-05 21:01 UTC, ityshchenko commented on my_project/urls.py
> +    path('password_change/', include('django.contrib.auth.urls')),
It would be better if all developers use `-` for url instead of `_`.

2020-11-05 21:43 UTC, Andrii-Mudrak commented on mainapp/models.py
> +    id = models.BigAutoField('id',primary_key=True)
done

2020-11-05 21:43 UTC, Andrii-Mudrak commented on mainapp/models.py
> +    autor_id = models.ForeignKey('User_agent', on_delete=models.SET_NULL, null=True)
done

2020-11-05 21:44 UTC, Andrii-Mudrak commented on mainapp/models.py
> +    autor_id = models.ForeignKey('User_agent', on_delete=models.SET_NULL, null=True)
done

2020-11-05 21:45 UTC, Andrii-Mudrak commented on mainapp/models.py
> +    user_id = models.ForeignKey('User_agent', on_delete=models.SET_NULL, null=True)
done

2020-11-05 21:57 UTC, Andrii-Mudrak commented on my_project/settings.py
> +#DATABASES['default'] = dj_database_url.config(os.getenv('DATABASE_URL', 'sqlite:///./db.sqlite3'))
when I use DATABASE_URL I receive empty dict in DATABASE engine. I spend more then two days

2020-11-05 22:04 UTC, Andrii-Mudrak commented on my_project/urls.py
> +    path('password_change/', include('django.contrib.auth.urls')),
I will solve it in the next project )))
I don`t want make some change if it works

2020-11-07 18:36 UTC, Andrii-Mudrak commented on mainapp/templates/mainapp/basic.html
> +        {% endif%}
fixed

2020-11-07 18:37 UTC, Andrii-Mudrak commented on mainapp/templates/mainapp/home.html
> +{% endblock %}
fixed

2020-11-07 18:39 UTC, Andrii-Mudrak commented on mainapp/templates/registration/password_reset_confirm.html
> +            {{form.as_p}}
fixed

2020-11-07 18:42 UTC, Andrii-Mudrak commented on mainapp/templates/registration/password_reset_confirm.html
> +        <p style="color:red;">Неправильний токен</p>
fixed

2020-11-07 19:49 UTC, Andrii-Mudrak commented on mainapp/views.py
fixed

2020-11-07 19:50 UTC, Andrii-Mudrak commented on mainapp/templates/registration/password_reset_email.html
> +{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
ok

2020-11-07 19:50 UTC, Andrii-Mudrak commented on mainapp/templates/registration/password_reset_confirm.html
> +        <p style="color:red;">Неправильний токен</p>
fixed

2020-11-07 21:32 UTC, TihonV requested changes

2020-11-07 21:32 UTC, TihonV commented on mainapp/models.py
> +    user_id = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
1. `models.ForeignKey` (many-to-one). Single user would have none or many comments.
2. Must relate to `Profile` instead of `AUTH_USER_MODEL`.

2020-11-07 21:32 UTC, TihonV commented on mainapp/models.py
> +    autor = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
1. `author` (typo).
2. `models.ForeignKey` (many-to-one). Same as for `Comment` (see above).

2020-11-07 21:32 UTC, TihonV commented on mainapp/models.py
> +    autor = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
1. `author` (typo)
2. m2o

2020-11-07 21:32 UTC, TihonV commented on mainapp/models.py
> +    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
`models.ForeignKey` (m2o). Single product would have many responses.

2020-11-07 21:32 UTC, TihonV commented on mainapp/models.py
>      deleted_at = models.DateTimeField('deleted _at', null=True)
`'deleted _at'` has unexpected space for column name.

2020-11-07 21:32 UTC, TihonV commented on mainapp/templates/mainapp/basic.html
> +    <meta charset = "UTF-8">
HTML doesn't allow white-space between attribute and value.

2020-11-07 21:32 UTC, TihonV commented on mainapp/templates/mainapp/home.html
>  <h1 align="center">Вітаю на сайті, {% if user.is_authenticated %}{{ user.username }}{% else%}гість{% endif %} </h1>
Missed white-space after `else` tag

2020-11-07 21:32 UTC, TihonV commented on mainapp/templates/mainapp/basic.html
> +        {% endif%}
Nope. It's about white-space after `endif`. All tags must be padded with white-space.

2020-11-07 21:32 UTC, TihonV commented on mainapp/templates/registration/password_reset_confirm.html
> +        <p style = "alert alert-danger" role = "alert">Неправильний токен</p>
Looks good for me.

2020-11-07 21:32 UTC, TihonV commented on mainapp/templates/registration/password_reset_email.html
> +<a href="{{ request.scheme }}://{{ request.get_host }}{% url 'password_reset_confirm' uidb64=uid token=token %}/">Confirm account</a>
Good habit to add single empty row to end of file.

2020-11-07 21:32 UTC, TihonV commented on mainapp/views.py
> +    count: Any = User.objects.count()
Don't add `Any` typing to un-typed functions. Make all object (including attributes) are typed or add docstring.

2020-11-07 21:32 UTC, TihonV commented on mainapp/views.py
> +    count: Any = User.objects.count()
See Example:

```python3
from django.http import HttpRequest, Responce 

def home(request: HttpRequest) -> Responce:
    count: int = User.objects.count()  # That's count and it always int
    return render(request, 'mainapp/home.html', {'count': count})

```

2020-11-07 21:32 UTC, TihonV commented on mainapp/views.py
> +    count: Any = User.objects.count()
That's hasn't no sense because Django hasn't build-ins typing.

2020-11-07 21:32 UTC, TihonV commented on my_project/settings.py
>  DATABASES = {
Next snippet is enough for dj_database_url. Don't repeat yourself.
```
DATABASES = dict()
DATABASES['default'] = dj_database_url.config(default='sqlite:///./db.sqlite3') 
```

2020-11-07 21:32 UTC, TihonV commented on my_project/settings.py
>  print(DATABASES)
Remove `print` from code. Use named-logger with debug-level instead of this.

2020-11-07 21:33 UTC, TihonV commented on mainapp/models.py
> +    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
Use lazy naming to related models
```python3
product = models.ForeignKey('Product', on_delete=models.SET_NULL, null=True)
```

2020-11-08 22:29 UTC, TihonV requested changes

2020-11-08 22:29 UTC, TihonV commented on mainapp/models.py
> +    autor = models.ForeignKey('Profile', on_delete=models.SET_NULL, null=True)
author (typo)

2020-11-08 22:29 UTC, TihonV commented on mainapp/models.py
> +    deleted_time = datetime.now() + timedelta(days=10)
It doesn't works in this way. `deleted_time` will be calculated only once after app starting.
You can create separated function for default value

```python3
from django.db import models

def autodelete_date(delta=timedelta(days=10)):
    return F('updated_at') - delta


class Profile(models.Model):
    updated_at = models.DateTimeField('updated_at', auto_now=True, auto_now_add=True)
    deleted_at = models.DateTimeField('deleted_at', default=autodelete_date)
```

By the way, it's acceptable for deactivating `Products` but auto-deleting `Profiles` is bad idea.

2020-11-08 22:29 UTC, TihonV commented on mainapp/models.py
> +    deleted_at = models.DateTimeField('deleted _at', null=True, default=deleted_time)
You pass typo again. Unexpected space in column name.

```
deleted_at = models.DateTimeField('deleted _at', null=True, default=deleted_time)
                                        # ^ here
```

2020-11-16 17:55 UTC, ityshchenko commented on mainapp/migrations/0001_squashed_0004_auto_20201111_1937.py
> +                ('author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
You have ForeignKey at models. Look like django migration don't see difference between 1to1 & 1to-many.

2020-11-16 17:55 UTC, ityshchenko commented on mainapp/views.py
> +            return render(request, 'mainapp/home.html')
Better to use temporary redirect
```python3
from django.shortcuts import redirect


def _(request):
    return redirect('/', permanent=False)

```

2020-12-26 07:23 UTC, closed without merging